CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers (
  id INT NOT NULL AUTO_INCREMENT,
  burger VARCHAR(255) NOT NULL,
  devoured BOOLEAN DEFAULT false,
  toGo BOOLEAN DEFAULT false,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (id)
);